name: Metadata Validation

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Get changed files
      id: get_changed
      uses: tj-actions/changed-files@v44
      with:
        files: "*-test-samples/**/metadata.json"
        separator: ","

    - name: Echo changed files
      id: setfiles
      run: |
        files=${{ steps.get_changed.outputs.all_changed_files }}
        echo $files
        echo "FILES=$files" >> $GITHUB_OUTPUT

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install requirements
      run: pip install -r .github/metadata/requirements.txt

    - name: Validate Schema
      run: python .github/metadata/metadata_json_validator.py ${{ steps.get_changed.outputs.all_changed_files }}