name: Metadata Validation Pattern Submission Workflow

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Get changed files using defaults
      id: get_changed
      uses: tj-actions/changed-files@v44
      with:
        files: "*-test-samples/*/*.json"
        separator: ","

    - name: Echo changed files
      id: setfiles
      run: |
        files=${{ steps.get_changed.outputs.all_changed_files }}
        echo $files
        echo "FILES=$files" >> $GITHUB_OUTPUT

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Get new folder
      id: setfolders
      run: |
        python -m pip install --upgrade pip
        pip install github-action-utils
        python .github/workflows/getPatternFolder.py "${{ steps.setfiles.outputs.FILES }}"

    - name: Validate Schema
      run: |
        for folder in ${{ steps.setfolders.outputs.folders }}
        do
          echo $folder
          pip install -r .github/workflows/requirements.txt
          python .github/workflows/metadata_json_validator.py $folder
        done